apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o ../../kubernetes/service
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: user-rpc
  name: user-rpc
spec:
  ports:
    - name: "9100"
      port: 9100
      targetPort: 9000
  selector:
    io.kompose.service: user-rpc
status:
  loadBalancer: {}
