filebeat.inputs:
  - type: log
    enabled: true
    # 开启json解析
    json.keys_under_root: true
    json.add_error_key: true
    #容器中目录下的所有.log文件
    paths:
      - /usr/share/code/logs/*.log
      - /usr/share/code/logs/user/api/*.log

setup.template.settings:
  index.number_of_shards: 1

# 定义kafka topic field
fields:
  log_topic: log-collection

# 输出到kafka
output.kafka:
  hosts: ["kafka:9092"]
  topic: "%{[fields.log_topic]}"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  keep_alive: 10s

# ================================= Processors =================================
processors:
  - decode_json_fields:
      fields: ["@timestamp", "level", "content", "trace", "span", "duration"]
      target: ""
