version: "3.8"

# 申明同一个网络
networks:
  mf_net:
    name: mf_net
    # external: true # 申明网络已经在外部创建

    # 游戏数据卷
volumes:
  mf_etcd_data:
    driver: local
  mf_redisdata:
    driver: local
  mf_nginxdata:
    driver: local
  mf_mysql8data:
    driver: local
  # 服务
services:
  mf_etcd:
    image: bitnami/etcd:latest
    restart: always    
    ports:
      - 2379:2379
      - 2380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://vb-dev:2379
    volumes:
      - mf_etcd_data:/bitnami/etcd
    networks:
      - mf_net

  mf_etcd_web:
    image: evildecay/etcdkeeper
    restart: always    
    ports:
      - 9080:8080
    networks:
      - mf_net
    # entrypoint: [ "./etcdkeeper.bin", "-h", 0.0.0.0, -p, 8080 ]

  mf_redis:
    image: redis:6.0.2-alpine
    container_name: mf_redis_6.0.2
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mf_net
    command: /usr/local/etc/redis/redis.conf
    volumes:
      # 持久存储redis的数据
      - mf_redisdata:/data
      # 挂载本地配置文件
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - /etc/localtime:/usr/local/etc/localtime

  mf_mysql8:
    image: mysql:8.0.24
    container_name: mf_mysql_8.0.24
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - mf_net
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    working_dir: /home
    volumes:
      - ./mysql/8.0.24/conf/docker.cnf:/etc/mysql/conf.d/docker.cnf:rw
      - mf_mysql8data:/var/lib/mysql/:rw
      - mf_mysql8data:/var/log/mysql/:rw
      - ./sql:/data/sql/:rw
      - /etc/localtime:/usr/local/etc/localtime
      - ./mysql/8.0.24/exec.sh:/home/exec.sh