version: "3.8"

# 申明同一个网络
networks:
  mf_net:
    name: mf_net
    external: true

# 服务
services:
  user-api:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    ports:
      - 8000:8000
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "api", "user" ]

  user-rpc:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    ports:
      - 9100:9000
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "rpc", "user" ]

  product-api:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    ports:
      - 8001:8001
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "api", "product" ]

  product-rpc:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "rpc", "product" ]

  order-api:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    ports:
      - 8002:8002
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "api", "order" ]

  order-rpc:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "rpc", "order" ]

  pay-api:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    ports:
      - 8003:8003
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "api", "pay" ]

  pay-rpc:
    image: golang:1.17.5-buster
    tty: true
    working_dir: /home/code
    restart: always
    user: 1000:1000
    networks:
      - mf_net
    env_file:
      - .go.env
    volumes:
      - ../:/home/code
    entrypoint: [ "./start.sh", "rpc", "pay" ]
