Name: product.rpc
ListenOn: 0.0.0.0:9001

Etcd:
  Hosts:
    - mf_etcd:2379
  Key: product.rpc

Mysql:
  DataSource: root:12345@tcp(mf_mysql8:3306)/mf_mall?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: mf_redis:6379
    Type: node
    Pass: "12345"

Telemetry:
  Name: product.rpc
  Endpoint: http://mf_jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: jaeger
